# # # # # # # # # # # # # # # # #
#  CustomSpawners Configuration #
#       By thebiologist13       #
# # # # # # # # # # # # # # # # #

spawners:

    # Default Spawner Properties
    # These properties are just what is given to a spawner
    # when it is created; they can be changed at any time.
    
    # Radius of area a spawner can spawn in.
    radius: 8
    
    # If a spawner block needs to be powered to spawn mobs.
    redstoneTriggered: false
    
    # Maximum distance a player can be from a spawner for
    # it to spawn.
    maxPlayerDistance: 16
    
    # Minimum distance a player can be from a spawner for
    # it to spawn.
    minPlayerDistance: 0
    
    # Should the spawner actually spawn when created?
    active: false
    
    # Maximum light level on a spawner for
    # it to be able to spawn. (put value 0-15)
    maxLightLevel: 7
    
    # Minimum light level on a spawner for
    # it to be able to spawn. (put value 0-15)
    minLightLevel: 0
    
    # Should the spawner be "hidden" from players 
    # when they use spawner listing commands if they
    # do not have permission?
    hidden: false
    
    # What should the rate (in server ticks: 20 ticks/second)
    # that the spawner spawns mobs at? Make greater than 0.
    rate: 120
    
    # How many mobs should be spawned each time?
    mobsPerSpawn: 2
    
    # What should the maximum amount of mobs that a spawner
    # have spawned at one time?
    maxMobs: 12
    
    # Should spawners be capped for mobs by default?
    capped: false
    
    # Spawner limits
    # Limits of values for spawner properties. 
    # These can be overridden in permissions with
    # customspawners.limitoverride
    
    # Radius limit (max)
    radiusLimit: 128
    
    # MaxPlayerDistance maximum value
    playerDistanceLimit: 128
    
    # Rate limit (minimum amount of ticks)
    rateLimit: 10
    
    # Mobs per spawn limit
    mobsPerSpawnLimit: 16
    
    # Maximum mobs limit
    maxMobsLimit: 256
    
    
    
    # Miscellaneous Spawner Options
    
    # Should spawned mobs be killed when the
    # plugin is disabled, reloaded, or 
    # /customspawners reload is used. 
    # This saves time saving and loading spawners.
    killOnReload: false
    
    # Should spawners be disabled when their block is
    # destroyed?
    deactivateOnBreak: true
    
    # Should mobs created by a spawner
    # be removed when that spawner is removed?
    killOnRemove: true
    
    # Should the spawner be removed when its block
    # is broken?
    removeOnBreak: true
    
    # Should CustomSpawners ignore WorldGuard?
    ignoreWorldGuard: false
    
    # Should CustomSpawners ignore Heroes?
    ignoreHeroes: false
    
mobs:

    # Which mob types for entities should be 
    # unavailable on the server?
    # Add to the list to disable.
    blacklist:
        - giant
        - ender_dragon
        - ender_crystal
        - wither
        - ghast
        - blaze
    
players:
    # Maximum distance a player can be from a block
    # to set that block as a spawner.
    maxDistance: 5
    
    # Maximum distance a player can be from a spawner
    # to consider it "nearby". This is for the listnear
    # command.
    maxNear: 25

    # Item ID to use for selecting spawn area positions.
    selectionId: 269
    
    # Do you want to be warned and asked for confirmation before
    # running potentially extreme lag causing or dangerous commands?
    # CustomSpawners will wait for confirmation for the amount of time specified in "timeout" 
    # then cancel if the command is not entered again.
    warnLag: true
    
    # Amount of time (in seconds) to wait when warned.
    timeout: 5

data:
    
    # Would you like to turn the autosave feature on?
    # Spawners and entities are normally saved when the
    # plugin is disabled, but any other way of closing 
    # the server could cause a loss of data without
    # some of the autosave features enabled.
    autosave: true
    
    # Different times to autosave. 
    
    # Create a file when a spawner or entity is created?
    saveOnCreate: true
    
    # Save when any CustomSpawners command is issued.
    saveOnCommand: false
    
    # Save at an interval in time?
    saveOnClock: true
    
    # Interval in minutes between saves. This only applies
    # if saveOnClock is true. Note that having lots of
    # spawners and entities then having a short interval
    # here could cause lag.
    interval: 10
    
    # Broadcast a save message to the server when saving?
    broadcastAutosave: true
    
    # Should the save message only be broadcast to OPs?
    broadcastOnlyOp: true
    
    # Broadcast Message for start of save.
    broadcastMessage: CustomSpawners is saving spawners and entities! Expect some lag!
    
    # Broadcast Message for end of save.
    broadcastMessageEnd: Done saving spawners and entities.
    
    # How much info should be printed to the console?
    # 0 is no saving/loading info, 1 is some saving/loading info,
    # and 2 is all saving/loading info.
    logLevel: 2
    
    # Developer Debug Mode
    # Leave false unless you want endless console spam.
    debug: false
    