# # # # # # # # # # # # # # # # #
#  CustomSpawners Configuration #
#       By thebiologist13       #
# # # # # # # # # # # # # # # # #

spawners:

    # Default Spawner Properties
    # These properties are just what is given to a spawner
    # when it is created; they can be changed at any time.
    
    # Radius of area a spawner can spawn in.
    radius: 16
    
    # If a spawner block needs to be powered to spawn mobs.
    redstoneTriggered: false
    
    # Maximum distance a player can be from a spawner for
    # it to spawn.
    maxPlayerDistance: 32
    
    # Minimum distance a player can be from a spawner for
    # it to spawn.
    minPlayerDistance: 0
    
    # Should the spawner actually spawn when created?
    active: false
    
    # Maximum light level on a spawner for
    # it to be able to spawn. (put value 0-15)
    maxLightLevel: 7
    
    # Minimum light level on a spawner for
    # it to be able to spawn. (put value 0-15)
    minLightLevel: 0
    
    # Should the spawner be "hidden" from players 
    # when they use spawner listing commands if they
    # do not have permission?
    hidden: false
    
    # What should the rate (in server ticks: 20 ticks/second)
    # that the spawner spawns mobs at?
    rate: 120
    
    # How many mobs should be spawned each time?
    mobsPerSpawn: 2
    
    # What should the maximum amount of mobs that a spawner
    # have spawned at one time?
    maxMobs: 64
    
    
    
    # Spawner limits
    # Limits of values for spawner properties. 
    # These can be overridden in permissions.
    
    # Radius limit (max)
    radiusLimit: 128
    
    # MaxPlayerDistance maximum value
    playerDistanceLimit: 128
    
    # Rate limit (minimum amount of ticks)
    rateLimit: 10
    
    # Mobs per spawn limit
    mobsPerSpawnLimit: 16
    
    # Maximum mobs limit
    maxMobsLimit: 256
    
    
    
    # Miscellaneous Spawner Options
    
    # Should spawned mobs be killed when the
    # plugin is disabled, reloaded, or 
    # /customspawners reload is used. 
    # This saves time saving and loading spawners.
    killOnReload: false

entities:
    
    # Default Entity Properties
    # These properties are just what is given to an entity
    # when it is created; they can be changed at any time.
    
    # Base type of mob. Note that zombie pigmen are 
    # "pigzombie" and ocelots are "ozelot".
    type: pig
    
    # Starting age of an entity. Make this an integer
    # or use "BABY" for a baby animal or "ADULT" for 
    # an adult animal.
    age: ADULT
    
    # Starting health of an entity. Make this an integer
    # but keep in mind every increment of 1 is 1/2 a heart.
    # Use "MINIMUM" for a mob with minimum health (1/2 heart)
    # and "MAXIMUM" for the mob's maximum amount of health.
    health: MAXIMUM
    
    # Starting air for an entity. Useful if the spawner is deep
    # under water/lava. Use "MINIMUM" for no air and "MAXIMUM"
    # for a full bubble meter for that mob.
    air: MAXIMUM
    
    # Starting profession of a villager. Allowed values are
    # "BLACKSMITH", "BUTCHER", "FARMER", "LIBRARIAN", and
    # "PRIEST".
    profession: FARMER
    
    # Block ID an enderman will be holding. Not all blocks will
    # work. Default is grass.
    endermanBlock: 2
    
    # Boolean values for some properties. The name should be
    # self-explanatory.
    isSaddled: false
    isCharged: false
    isJockey: false
    isTamed: false
    isAngry: false
    isSitting: false
    
    # Default type of cat an ocelot is. Allowed values are
    # "BLACK_CAT", "RED_CAT", and "SIAMESE_CAT". Use "NONE"
    # for a wild ocelot.
    catType: NONE
    
    # Size of slimes and magma cubes. Use an integer value
    # from 1 to 256. Keep in mind the largest natural slimes
    # are only a 4 in size!
    slimeSize: 1
    
    # Color of sheep when spawned. Allowed values are "BLACK",
    # "BLUE", "BROWN", "CYAN", "GREY", "GREEN", "LIGHT_BLUE",
    # "LIME", "MAGENTA", "ORANGE", "PINK", "PURPLE", "RED",
    # "SILVER", "WHITE", and "YELLOW".
    color: WHITE 
     
mobs:

    # Which mob types for entities should be 
    # unavailable on the server?
    # Set false to disable.
    pig: true
    cow: true
    mushroom_cow: true
    sheep: true
    chicken: true
    wolf: true
    ocelot: true
    squid: true
    villager: true
    spiderjockey: true
    zombie: true
    skeleton: true
    creeper: true
    spider: true
    enderman: true
    ender_dragon: false
    giant: false
    silverfish: true
    cave_spider: true
    slime: true
    magma_cube: true
    pig_zombie: true
    ghast: false
    blaze: false
    iron_golem: true
    snowman: true
    
players:
    # Maximum distance a player can be from a block
    # to set that block as a spawner. May be limited
    # by power of server, but at least 100 blocks always.
    maxDistance: 50
    
    # Maximum distance a player can be from a spawner
    # to consider it "nearby". This is for the listnear
    # command.
    maxNear: 25
    