name: CustomSpawners
version: 0.0.1
author: thebiologist13
description: Make any block a simulated mob spawner and configure it's properties.
main: com.github.thebiologist13.CustomSpawners
commands:
    customspawners:
        description: The main command of CustomSpawners. Other commands branch off this one.
        usage: This command is used by: /customspawners [subcommand] [arguments...] Refer to CustomSpawner's BukkitDev for more usage help.
        aliases: [cs, csplugin]
        permission: customspawners.customspawners
        permission-message: You do not have permission to use the customspawner command.
    spawners:
        description: This command executes spawner-related functions.
        usage: This command is used by: /spawners [subcommand] [arguments...] Refer to CustomSpawner's BukkitDev for more usage help.
        aliases: [css, csspawners]
        permission: customspawners.spawners
        permission-message: You do not have permission to use the spawners command.
    entities:
        description: This command executes entity-related functions.
        usage: This command is used by: /entities [subcommand] [arguments...] Refer to CustomSpawner's BukkitDev for more usage help.
        aliases: [cse, csentities]
        permission: customspawners.entities
        permission-message: You do not have permission to use the entities command.
permissions:
    customspawners.customspawners:
        description: Allows the user/group to use the "/customspawner" command. Does not cover all sub-commands. Use customspawners.* for that.
        default: true
    customspawners.help:
        description: Allows the user/group to use the "/customspawner help" command. Does not cover all sub-commands. Use customspawners.* for that.
        default: true
    customspawners.reloadspawners:
        description: Allows the user/group to reload spawners from file.
        default: false
    customspawners.spawners.listnear:
        description: Allows the user/group to use the "/customspawner listnear" command.
        default: true
    customspawners.spawners.listall:
        description: Allows the user/group to use the "/customspawner listall" command.
        default: true
    customspawners.spawners.listnear.hidden:
        description: Allows the user/group to use the "/customspawner listnear" command. Also allows then to see nearby hidden spawners.
        default: false
    customspawners.spawners.listall.hidden:
        description: Allows the user/group to use the "/customspawner listnear" command. Also allows them to see hidden spawners.
        default: false
    customspawners.spawners.create:
        description: Allows the user/group to create spawners.
        default: false
    customspawners.spawners.remove:
        description: Allows the user/group to remove spawners.
        default: false
    customspawners.spawners.select:
        description: Allows the user/group to select spawners.
        default: true
    customspawners.spawners.limitoverride:
        description: Allows the user/group to ignore the spawner property limits from config.
        default: false
    customspawners.spawners.setactive:
        description: Allows the user/group to set spawners active.
        default: false
    customspawners.spawners.setinactive:
        description: Allows the user/group to set spawners inactive.
        default: false
    customspawners.spawners.sethidden:
        description: Allows the user/group to set spawners hidden
        default: false
    customspawners.spawners.setunhidden:
        description: Allows the user/group to set spawners unhidden.
        default: false
    customspawners.spawners.setmaxlight:
        description: Allows the user/group to set the maximum light level a spawner can spawn at.
        default: false
    customspawners.spawners.setminlight:
        description: Allows the user/group to set the minimum light level a spawner can spawn at.
        default: false
    customspawners.spawners.setmaxmobs:
        description: Allows the user/group to set the maximum amount a mobs a single spawner can spawn.
        default: false
    customspawners.spawners.setmobsperspawn:
        description: Allows the user/group to set the mobs a spawner with spawn each time.
        default: false
    customspawners.spawners.setmaxdistance:
        description: Allows the user/group to set the maximum distance players can be from a spawner.
        default: false
    customspawners.spawners.setmindistance:
        description: Allows the user/group to set the minimum distance players can be from a spawner.
        default: false
    customspawners.spawners.setlocation:
        description: Allows the user/group to set a new location for a spawner.
        default: false
    customspawners.spawners.setradius:
        description: Allows the user/group to set the spawn radius of a spawner.
        default: false
    customspawners.spawners.setrate:
        description: Allows the user/group to set the spawn rate of a spawner.
        default: false
    customspawners.spawners.setredstone:
        description: Allows the user/group to set whether a spawner only works when triggered by redstone.
        default: false
    customspawners.spawners.settype:
        description: Allows the user/group to set the type of mob a spawner spawns.
        default: false
    customspawners.spawners.info:
        description: Allows the user/group to see info about a spawner.
        default: true
    customspawners.spawners.info.hidden:
        description: Allows the user/group to see info about a spawner (including hidden ones).
        default: false