name: CustomSpawners
version: 0.0.6
author: thebiologist13
description: Make any block a simulated mob spawner and configure it's properties.
main: com.github.thebiologist13.CustomSpawners
softdepend: [WorldGuard, WorldEdit]
loadbefore: [WorldGuard, WorldEdit]
commands:
    customspawners:
        description: The main command of CustomSpawners. Other commands branch off this one.
        usage: This command is used by /customspawners [subcommand] [arguments...] Refer to CustomSpawner's BukkitDev for more usage help.
        aliases: [cs, csplugin]
        permission: customspawners.customspawners
        permission-message: You do not have permission to use the customspawner command.
    spawners:
        description: This command executes spawner-related functions.
        usage: This command is used by /spawners [subcommand] [arguments...] Refer to CustomSpawner's BukkitDev for more usage help.
        aliases: [css, csspawners]
        permission: customspawners.spawners
        permission-message: You do not have permission to use the spawners command.
    entities:
        description: This command executes entity-related functions.
        usage: This command is used by /entities [subcommand] [arguments...] Refer to CustomSpawner's BukkitDev for more usage help.
        aliases: [cse, csentities]
        permission: customspawners.entities
        permission-message: You do not have permission to use the entities command.
permissions:
    customspawners.*:
        description: Gives access to all of CustomSpawners' features.
        default: op
        children:
            customspawners.customspawners: true
            customspawners.help: true
            customspawners.reloadspawners: true
            customspawners.limitoverride: true
            customspawners.spawners.activateall: true
            customspawners.spawners.deactivateall: true
            customspawners.spawners.forcespawn: true
            customspawners.spawners.listnear: true
            customspawners.spawners.listall: true
            customspawners.spawners.listnear.hidden: true
            customspawners.spawners.listall.hidden: true
            customspawners.spawners.create: true
            customspawners.spawners.remove: true
            customspawners.spawners.select: true
            customspawners.spawners.setactive: true
            customspawners.spawners.setinactive: true
            customspawners.spawners.sethidden: true
            customspawners.spawners.setunhidden: true
            customspawners.spawners.setmaxlight: true
            customspawners.spawners.setminlight: true
            customspawners.spawners.setmaxmobs: true
            customspawners.spawners.setmobsperspawn: true
            customspawners.spawners.setmaxdistance: true
            customspawners.spawners.setmindistance: true
            customspawners.spawners.setlocation: true
            customspawners.spawners.setradius: true
            customspawners.spawners.setrate: true
            customspawners.spawners.setredstone: true
            customspawners.spawners.addtype: true
            customspawners.spawners.settype: true
            customspawners.spawners.info: true
            customspawners.spawners.info.hidden: true
            customspawners.spawners.setname: true
            customspawners.spawners.setspawnarea: true
            customspawners.spawners.position: true
            customspawners.spawners.convert: true
            customspawners.entities.setpassive: true
            customspawners.entities.create: true
            customspawners.entities.select: true
            customspawners.entities.remove: true
            customspawners.entities.info: true
            customspawners.entities.setname: true
            customspawners.entities.settype: true
            customspawners.entities.seteffect: true
            customspawners.entities.addeffect: true
            customspawners.entities.setage: true
            customspawners.entities.setair: true
            customspawners.entities.setangry: true
            customspawners.entities.setcattype: true
            customspawners.entities.setcharged: true
            customspawners.entities.cleareffects: true
            customspawners.entities.setcolor: true
            customspawners.entities.setenderblock: true
            customspawners.entities.sethealth: true
            customspawners.entities.info: true
            customspawners.entities.setjockey: true
            customspawners.entities.setprofession: true
            customspawners.entities.setsaddled: true
            customspawners.entities.settype: true
            customspawners.entities.setsitting: true
            customspawners.entities.setslimesize: true
            customspawners.entities.settamed: true
            customspawners.entities.setvelocity: true
            customspawners.entities.listall: true
            customspawners.entities.setfireticks: true
            customspawners.entities.blacklist: true
            customspawners.entities.whitelist: true
            customspawners.entities.itemlist: true
            customspawners.entities.setcustomdamage: true
            customspawners.entities.setdamageamount: true
            customspawners.entities.adddrop: true
            customspawners.entities.setdrop: true
            customspawners.entities.cleardrop: true
            customspawners.entities.setusingdrops: true
            customspawners.entities.setpotiontype: true
            customspawners.entities.setexp: true
            customspawners.entities.setfuselength: true
            customspawners.entities.setyield: true
            customspawners.entities.setincendiary: true
            customspawners.entities.setitemtype: true
            customspawners.entities.setinvulnerable: true
            customspawners.entities.inventory: true
            customspawners.entities.setwither: true
    customspawners.customspawners:
        description: Allows the user/group to use the "/customspawner" command. Does not cover all sub-commands. Use customspawners.* for that.
        default: true
    customspawners.help:
        description: Allows the user/group to use the "/customspawner help" command. Does not cover all sub-commands. Use customspawners.* for that.
        default: true
    customspawners.reloadspawners:
        description: Allows the user/group to reload spawners from file.
        default: op
    customspawners.spawners.activateall:
        description: Allows the user/group to activate all spawners.
        default: op
    customspawners.spawners.deactivateall:
        description: Allows the user/group to deactivate all spawners.
        default: op
    customspawners.spawners.forcespawn:
        description: Allows the user/group to force a spawner to spawn an entity.
        default: op
    customspawners.spawners.listnear:
        description: Allows the user/group to use the "/customspawner listnear" command.
        default: true
    customspawners.spawners.listall:
        description: Allows the user/group to use the "/customspawner listall" command.
        default: true
    customspawners.spawners.listnear.hidden:
        description: Allows the user/group to use the "/customspawner listnear" command. Also allows then to see nearby hidden spawners.
        default: op
    customspawners.spawners.listall.hidden:
        description: Allows the user/group to use the "/customspawner listnear" command. Also allows them to see hidden spawners.
        default: op
    customspawners.spawners.create:
        description: Allows the user/group to create spawners.
        default: op
    customspawners.spawners.remove:
        description: Allows the user/group to remove spawners.
        default: op
    customspawners.spawners.select:
        description: Allows the user/group to select spawners.
        default: true
    customspawners.spawners.limitoverride:
        description: Allows the user/group to ignore the spawner property limits from config.
        default: op
    customspawners.spawners.setactive:
        description: Allows the user/group to set spawners active.
        default: op
    customspawners.spawners.setinactive:
        description: Allows the user/group to set spawners inactive.
        default: op
    customspawners.spawners.sethidden:
        description: Allows the user/group to set spawners hidden
        default: op
    customspawners.spawners.setunhidden:
        description: Allows the user/group to set spawners unhidden.
        default: op
    customspawners.spawners.setmaxlight:
        description: Allows the user/group to set the maximum light level a spawner can spawn at.
        default: op
    customspawners.spawners.setminlight:
        description: Allows the user/group to set the minimum light level a spawner can spawn at.
        default: op
    customspawners.spawners.setmaxmobs:
        description: Allows the user/group to set the maximum amount a mobs a single spawner can spawn.
        default: op
    customspawners.spawners.setmobsperspawn:
        description: Allows the user/group to set the mobs a spawner with spawn each time.
        default: op
    customspawners.spawners.setmaxdistance:
        description: Allows the user/group to set the maximum distance players can be from a spawner.
        default: op
    customspawners.spawners.setmindistance:
        description: Allows the user/group to set the minimum distance players can be from a spawner.
        default: op
    customspawners.spawners.setlocation:
        description: Allows the user/group to set a new location for a spawner.
        default: op
    customspawners.spawners.setradius:
        description: Allows the user/group to set the spawn radius of a spawner.
        default: op
    customspawners.spawners.setrate:
        description: Allows the user/group to set the spawn rate of a spawner.
        default: op
    customspawners.spawners.setredstone:
        description: Allows the user/group to set whether a spawner only works when triggered by redstone.
        default: op
    customspawners.spawners.addtype:
        description: Allows the user/group to add a type of mob a spawner creates.
        default: op
    customspawners.spawners.settype:
        description: Allows the user/group to set the type of mob a spawner spawns.
        default: op
    customspawners.spawners.info:
        description: Allows the user/group to see info about a spawner.
        default: true
    customspawners.spawners.info.hidden:
        description: Allows the user/group to see info about a spawner (including hidden ones).
        default: op
    customspawners.spawners.setname:
        description: Allows the user/group to set the name of a spawner.
        default: op
    customspawners.spawners.setspawnarea:
        description: Allows the user/group to set the spawn area of a spawner..
        default: op
    customspawners.spawners.position:
        description: Allows the user/group to set spawn area positions.
        default: op
    customspawners.spawners.convert:
        description: Allows the user/group to convert spawners.
        default: op
    customspawners.entities.setpassive:
        description: Allows the user/group to set the mobs passive.
        default: op
    customspawners.entities.create:
        description: Allows the user/group to create a spawnable entity.
        default: op
    customspawners.entities.select:
        description: Allows the user/group to select a spawnable entity.
        default: op
    customspawners.entities.remove:
        description: Allows the user/group to remove a spawnable entity.
        default: op
    customspawners.entities.info:
        description: Allows the user/group to see info about a spawnable entity.
        default: op
    customspawners.entities.setname:
        description: Allows the user/group to set the name of a entity.
        default: op
    customspawners.entities.settype:
        description: Allows the user/group to set entity type of an entity.
        default: op
    customspawners.entities.seteffect:
        description: Allows the user/group to set potion effect of an entity.
        default: op
    customspawners.entities.addeffect:
        description: Allows the user/group to set entity type of an entity.
        default: op
    customspawners.entities.setage:
        description: Allows the user/group to set the age of an entity.
        default: op
    customspawners.entities.setair:
        description: Allows the user/group to set the air of an entity.
        default: op
    customspawners.entities.setangry:
        description: Allows the user/group to set if an entity is angry.
        default: op
    customspawners.entities.setcattype:
        description: Allows the user/group to set the cat type.
        default: op
    customspawners.entities.setcharged:
        description: Allows the user/group to set the entity charged.
        default: op
    customspawners.entities.cleareffects:
        description: Allows the user/group to clear potion effects on an entity.
        default: op
    customspawners.entities.setcolor:
        description: Allows the user/group to set the color.
        default: op
    customspawners.entities.setenderblock:
        description: Allows the user/group to set the block an enderman is holding.
        default: op
    customspawners.entities.sethealth:
        description: Allows the user/group to set the health of an entity.
        default: op
    customspawners.entities.info:
        description: Allows the user/group to get entity info.
        default: op
    customspawners.entities.setjockey:
        description: Allows the user/group to set if a spider is a jockey.
        default: op
    customspawners.entities.setprofession:
        description: Allows the user/group to set the villager profession.
        default: op
    customspawners.entities.setsaddled:
        description: Allows the user/group to set a pig saddled.
        default: op
    customspawners.entities.settype:
        description: Allows the user/group to set the base type of an entity.
        default: op
    customspawners.entities.setsitting:
        description: Allows the user/group to set a entity sitting.
        default: op
    customspawners.entities.setslimesize:
        description: Allows the user/group to set the size of slimes and magma cubes.
        default: op
    customspawners.entities.settamed:
        description: Allows the user/group to set an entity tamed.
        default: op
    customspawners.entities.setvelocity:
        description: Allows the user/group to set the velocity of an entity.
        default: op
    customspawners.entities.listall:
        description: Allows the user/group to see a list of all entities.
        default: true
    customspawners.entities.setfireticks:
        description: Allows the user/group to set how long a spawned entity is on fire.
        default: op
    customspawners.entities.blacklist:
        description: Allows the user/group to set values on the damage blacklist.
        default: op
    customspawners.entities.whitelist:
        description: Allows the user/group to set values on the damage whitelist.
        default: op
    customspawners.entities.itemlist:
        description: Allows the user/group to set values on the item list.
        default: op
    customspawners.entities.setcustomdamage:
        description: Allows the user/group to set the entity to use custom damage values.
        default: op
    customspawners.entities.setdamageamount:
        description: Allows the user/group to set the amount of damage dealt by an entity.
        default: op
    customspawners.entities.adddrop:
        description: Allows the user/group to add a drop for an entity.
        default: op
    customspawners.entities.setdrop:
        description: Allows the user/group to set the drops of an entity.
        default: op
    customspawners.entities.cleardrop:
        description: Allows the user/group to clear the entity drops.
        default: op
    customspawners.entities.setusingdrops:
        description: Allows the user/group to change whether the entity uses customized drops.
        default: op
    customspawners.entities.setpotiontype:
        description: Allows the user/group to set the type of potion of a spawned potion.
        default: op
    customspawners.entities.setexp:
        description: Allows the user/group to set the dropped exp.
        default: op
    customspawners.entities.setfuselength:
        description: Allows the user/group to set the fuse length.
        default: op
    customspawners.entities.setyield:
        description: Allows the user/group to set explosive yield.
        default: op
    customspawners.entities.setincendiary:
        description: Allows the user/group to set an explosive incendiary.
        default: op
    customspawners.entities.setitemtype:
        description: Allows the user/group to set the item type.
        default: op
    customspawners.entities.setinvulnerable:
        description: Allows the user/group to set a entity invulnerable.
        default: op
    customspawners.entities.inventory:
        description: Allows the user/group to modify entity inventories.
        default: op
    customspawners.entities.setwither:
        description: Allows the user/group to set the wither property.
        default: op